modLoader="javafml"
loaderVersion="[24,]"
issueTrackerURL="https://github.com/Clownvin/Living-Enchantment/issues"
displayURL="https://minecraft.curseforge.com/projects/living-enchantment"
logoFile="logo.png"

[[mods]]
    modId="livingenchantment"
    version="${file.jarVersion}"
    displayName="Living Enchantment"
    updateJSONURL="https://raw.githubusercontent.com/Clownvin/UpdateJSONs/master/livingenchantment.json"
    credits="Clownvin"
    authors="Clownvin"
    description='''
    A small and concise mod that adds living weapons and tools through an enchantment. Lots of config options.
    '''